export enum Configuration {
    PORT = "PORT",
    HOST = "HOST",
    USERNAME = "USERNAME",
    PASSWORD = "PASSWORD",
    DATABASE = "DATABASE",
    JWT_SECRET = "JWT_SECRET",
    JWT_EXPIRATION_TIME = "JWT_EXPIRATION_TIME",
    AWS_REGION = "AWS_REGION",
    AWS_ACCESS_KEY_ID = "AWS_ACCESS_KEY_ID",
    AWS_SECRET_ACCESS_KEY = "AWS_SECRET_ACCESS_KEY",
    AWS_PRIVATE_BUCKET_NAME = "AWS_PRIVATE_BUCKET_NAME"
}